# Generated by Django 5.0 on 2025-04-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='projectId',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
