# Generated by Django 5.0 on 2025-06-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='address',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
